blank_issues_enabled: false
contact_links:
  - name: Community Discussion
    url: https://github.com/Stevengre/siaan/discussions
    about: Please use Discussions for questions, ideas, and community conversations.
